### ISSUE TITLE
Borked on Ghost 0.9.0

### ISSUE THREAD

**Issue by hkfoster** [sethbrasile/ghost-cloudinary-store#11]
What we're currently seeing since upgrading to 0.9.0:

```
 npm info using npm@2.15.8

 > ghost@0.9.0 start /app
 npm info it worked if it ends with ok
 npm info start ghost@0.9.0
 > node index
 npm info prestart ghost@0.9.0
 npm info using node@v4.4.7

     at Function.Module._load (module.js:276:25)
     at Object.getStorage (/app/core/server/storage/index.js:25:30)
     at Object.<anonymous> (/app/content/storage/ghost-cloudinary-store/index.js:2:18)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:566:26)
     at Module._compile (module.js:409:26)
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
 ERROR: storage[storageChoice] is not a function 
     at setupMiddleware (/app/core/server/middleware/index.js:124:44)
     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:516:17) 
     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:516:17)
     at setupMiddleware (/app/core/server/middleware/index.js:124:44)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:566:26)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:561:18)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:561:18)
     at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:425:57)
     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
     at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:143:14)
 npm info ok 
     at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:630:18)
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:425:57)
  Error: Cannot find module 'cloudinary'
  TypeError: storage[storageChoice] is not a function
     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:504:31)
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:566:26)
     at Module.load (module.js:343:32)
     at Object.getStorage (/app/core/server/storage/index.js:19:34)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:561:18)
     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:16)
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:630:18)

 ERROR: Cannot find module 'cloudinary' 
     at Object.Module._extensions..js (module.js:416:10)
     at require (internal/module.js:12:17)
     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
     at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:125:19)
     at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:125:19)

     at Module.require (module.js:353:17)
     at Function.Module._resolveFilename (module.js:325:15)
     at require (internal/module.js:12:17)
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)


 npm info poststart ghost@0.9.0
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)
     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:504:31)
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)
     at Function.Module._load (module.js:300:12)

     at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:143:14)
     at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:630:18)
     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:606:10)
     at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:630:18)
     at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:630:18)
     at /app/core/server/index.js:130:9
     at /app/core/server/index.js:130:9
     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:685:18)
     at PromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/promise_array.js:143:14)
     at Module.require (module.js:353:17)
     at PromiseArray._resolve (/app/node_modules/bluebird/js/release/promise_array.js:125:19)
     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
```

This is following the current README .

**Comment by jvrsgsty** [comment]
@hkfoster 
The first error is actually linked to the second one: npm not being able to find the `cloudinary` module. 

I managed to get it to work by specifying the `cloudinary` and `ghost-cloudinary-store` as dependencies in Ghost's `package.json` and then shrinkwrapping again (apart from having copied the `ghost-cloudinary-store` module to the `storage/` folder). 

To do this, I installed the modules and shrinkwrapped as follows

```
npm install cloudinary --save
npm install ghost-cloudinary-store --save
npm shrinkwrap
```

 I am self hosting Ghost on Heroku, so commiting my changes and pushing my slug up for compilation did it for me. I know it is far from ideal having to install the dependencies in Ghost's core `package.json`.
perhaps somebody else has a more elegant solution?

**Comment by sethbrasile** [comment]
I just did a fresh install of ghost 0.9.0 (locally) and followed the "npm install" directions in my readme, and everything worked swimmingly.

@hkfoster any advice on replicating your error?

**Comment by QzSG** [comment]
I am facing the same error, using ghost 0.10.0 with modification to add required delete function
Using bluemix though, out of 10 tries , the error keeps appearing, sometimes it magically manages to find the module and work, out of the 10 times it happened twice, both after churning out the same errors.

```
ERROR: Cannot find module 'cloudinary' 2016-09-07T23:34:54.069+0800
App/0 Error2016-09-07T23:34:54.069+0800
App/0 at Error.IncorrectUsage (/home/vcap/app/core/server/errors/incorrect-usage.js:3:18)2016-09-07T23:34:54.069+0800
App/0 at Object.getStorage (/home/vcap/app/core/server/storage/index.js:36:19)2016-09-07T23:34:54.069+0800
App/0 at Immediate.Async.drainQueues [as _onImmediate] (/home/vcap/app/node_modules/bluebird/js/release/async.js:17:14)2016-09-07T23:34:54.069+0800
App/0 at PromiseArray._promiseFulfilled (/home/vcap/app/node_modules/bluebird/js/release/promise_array.js:143:14)2016-09-07T23:34:54.069+0800
App/0 at setupMiddleware (/home/vcap/app/core/server/middleware/index.js:126:44)2016-09-07T23:34:54.069+0800
App/0 at Promise._settlePromise (/home/vcap/app/node_modules/bluebird/js/release/promise.js:566:26)2016-09-07T23:34:54.069+0800
App/0 at Promise._settlePromises (/home/vcap/app/node_modules/bluebird/js/release/promise.js:685:18)2016-09-07T23:34:54.069+0800
App/0 at processImmediate [as _immediateCallback] (timers.js:383:17) 2016-09-07T23:34:54.069+0800
App/0 at /home/vcap/app/core/server/index.js:131:92016-09-07T23:34:54.069+0800
App/0 at Async._drainQueues (/home/vcap/app/node_modules/bluebird/js/release/async.js:148:10)2016-09-07T23:34:54.069+0800
App/0 at Promise._settlePromiseFromHandler (/home/vcap/app/node_modules/bluebird/js/release/promise.js:504:31)2016-09-07T23:34:54.069+0800
App/0 at Async._drainQueue (/home/vcap/app/node_modules/bluebird/js/release/async.js:138:16)2016-09-07T23:34:54.069+0800
App/0 at Promise._settlePromise0 (/home/vcap/app/node_modules/bluebird/js/release/promise.js:606:10)`
```

EDIT :
I know I should not be doing this.. however, adding cloudinary to main ghost package.json fixed the error instantly.

**Comment by jvrsgsty** [comment]
@QuartzSG I feel you. I've tried a couple other things but I still haven't been able to solve this without adding it to Ghost's `package.json` which should **not** be the case.

**Comment by jvrsgsty** [comment]
@sethbrasile 
In my case, you can replicate the error by following the instructions for [installing Ghost on Heroku](https://www.ghostforbeginners.com/how-to-install-ghost-on-heroku/)
The image hosting on Amazon S3 part would be replaced by the instructions on your Readme.
Not sure if your module is Ghost 0.10 compatible yet, but this happens with Ghost 0.9 for sure.

**Comment by sethbrasile** [comment]
Just want to verify that you folks are doing step 3 in the installation instructions:

`cp -r node_modules/ghost-cloudinary-store content/storage/ghost-cloudinary-store`

?

And then committing the changes?

**Comment by jvrsgsty** [comment]
Yup, `content/storage/ghost-cloudinary-store` is in my git repo, which I then push to Heroku.

**Comment by QzSG** [comment]
@sethbrasile Yeap followed the instructions to a tee.

Could it simply be a case of node using bluebird inside the main ghost apps node_modules instead of the one inside ghost-cloudinary-store?

**Comment by mmornati** [comment]
All should be ok and updated to Ghost 1.X now.
